//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesContent
    {
        public int Id { get; set; }
        public int PageID { get; set; }
        public int LangId { get; set; }
        public int ContentFieldID { get; set; }
        public int ContentFieldTypeID { get; set; }
        public string HtmlContent { get; set; }
        public string ImageContent { get; set; }
        public string FileContent { get; set; }
        public Nullable<System.DateTime> DateContent { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
