//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesFriendlyUrl
    {
        public int Id { get; set; }
        public int LangId { get; set; }
        public string Name { get; set; }
        public string FriendlyUrl { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
